{
 "title": "AccessPoint",
 "tags": [ "Omada" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "increase_interval", "query": "${VAR_INCREASE_INTERVAL}" },
   { "name": "device_type", "query": "${VAR_DEVICE_TYPE}" },
   { "name": "freq_5Ghz", "query": "${VAR_FREQ_5GHZ}" },
   { "name": "freq_24Ghz", "query": "${VAR_FREQ_24GHZ}" }
  ]
 },
 "panels": [
  {
   "title": "Transferred over radio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(radio_rx_bytes_total{deviceType=\"$device_type\"}[$__range]) + \n    increase(radio_tx_bytes_total{deviceType=\"$device_type\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transferred over ethernet",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(port_rx_bytes_total{deviceType=\"$device_type\"}[$__range]) + \n    increase(port_tx_bytes_total{deviceType=\"$device_type\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(radio_rx_bytes_total[$increase_interval]) + \n    rate(radio_tx_bytes_total[$increase_interval])\n) /8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channels utilization and interference",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(radio_rx_usage{deviceType=\"$device_type\"}) by (radioFrequency)",
     "legendFormat": "Rx Utilization {{radioFrequency}}"
    },
    {
     "expr": "avg(radio_tx_usage{deviceType=\"$device_type\"}) by (radioFrequency)",
     "legendFormat": "Tx Utilization {{radioFrequency}}"
    },
    {
     "expr": "avg(radio_interference{deviceType=\"$device_type\"}) by (radioFrequency)",
     "legendFormat": "Interference {{radioFrequency}}"
    }
   ]
  },
  {
   "title": "Wireless Config",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "radio_info{deviceType=\"$device_type\"}\n* on (macAddress) group_left(deviceName)\nmax(device_info{deviceType=\"$device_type\"} == 1) by (macAddress, deviceName)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5 GHz Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(radio_rx_bytes_total{radioFrequency=\"$freq_5Ghz\"}[$increase_interval]) + \n    rate(radio_rx_bytes_total{radioFrequency=\"$freq_5Ghz\"}[$increase_interval])\n) /8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2.4 GHz Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(radio_rx_bytes_total{radioFrequency=\"$freq_24Ghz\"}[$increase_interval]) + \n    rate(radio_rx_bytes_total{radioFrequency=\"$freq_24Ghz\"}[$increase_interval])\n) /8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Radio TX",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n    rate(radio_tx_bytes_total[$increase_interval])\n    * on (macAddress) group_left(deviceName)\n    max(device_info{deviceType=\"$device_type\"} == 1) by (macAddress, deviceName)    \n)/8",
     "legendFormat": "{{deviceName}}-{{radioFrequency}}"
    }
   ]
  },
  {
   "title": "Radio RX",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n    rate(radio_rx_bytes_total[$increase_interval])\n    * on (macAddress) group_left(deviceName)\n    max(device_info{deviceType=\"$device_type\"} == 1) by (macAddress, deviceName)    \n)/8",
     "legendFormat": "{{deviceName}}-{{radioFrequency}}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "(\n    increase(radio_rx_retry_packets_total{deviceType=\"$device_type\"}[$increase_interval]) +  \n    increase(radio_tx_retry_packets_total{deviceType=\"$device_type\"}[$increase_interval])\n)\n    * on (macAddress) group_left(deviceName)\n    max(device_info{deviceType=\"$device_type\"} == 1) by (macAddress, deviceName)  ",
     "legendFormat": "{{deviceName}}-{{radioFrequency}}"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "memory_usage{deviceType=\"$device_type\"}\n* on (macAddress, deviceType) group_left(deviceName)\n  max(device_info{deviceType=\"$device_type\"} == 1) by (macAddress,deviceType,deviceName)",
     "legendFormat": "RAM - {{deviceName}}"
    },
    {
     "expr": "cpu_usage{deviceType=\"$device_type\"}\n* on (macAddress, deviceType) group_left(deviceName)\n  max(device_info{deviceType=\"$device_type\"} == 1) by (macAddress,deviceType,deviceName)",
     "legendFormat": "CPU - {{deviceName}}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"AccessPoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Radio Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(radio_rx_bytes_total{deviceType=\"$device_type\"}[$increase_interval]) + \n    rate(radio_tx_bytes_total{deviceType=\"$device_type\"}[$increase_interval])\n) /8",
     "legendFormat": "Radio Throughput"
    }
   ]
  }
 ]
}