{
 "title": "Site overview",
 "tags": [ "Omada" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_name", "query": "${VAR_JOB_NAME}" },
   {
    "name": "device_name",
    "label": "Controler Name",
    "query": {
     "query": "label_values(device_last_seen{job=\"$job_name\"},device_name)"
    }
   },
   { "name": "rate_interval", "query": "${VAR_RATE_INTERVAL}" }
  ]
 },
 "panels": [
  {
   "title": "Clients count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deviceType) (device_clients_count{job=\"$job_name\", deviceType!=\"Gateway\"}) > 0",
     "legendFormat": "{{deviceType}}"
    }
   ]
  },
  {
   "title": "Data transferred over radio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (radioFrequency) (\n  abs(deriv(radio_rx_bytes_total[$rate_interval])) +\n  abs(deriv(radio_tx_bytes_total[$rate_interval]))\n) * $__range",
     "legendFormat": "{{radioFrequency}}"
    }
   ]
  },
  {
   "title": "Data transferred over wire",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deviceType) (\n  abs(deriv(port_tx_bytes_total[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total[$rate_interval]))\n) * $__range",
     "legendFormat": "{{deviceType}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{job=\"$job_name\"} \n* on (deviceType, macAddress) group_left(deviceName) \n  max(device_info{job=\"$job_name\"}) by (deviceType, macAddress, deviceName)",
     "legendFormat": "{{ deviceName }}"
    }
   ]
  },
  {
   "title": "Max radio interference",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(radio_interference{job=\"$job_name\"}) by (radioFrequency)",
     "legendFormat": "{{radioFrequency}}"
    }
   ]
  },
  {
   "title": "Max radio usage by frequency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"radio_.*_usage\",job=\"$job_name\"}) by (radioFrequency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max radio usage by frequency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"radio_.*_usage\",job=\"$job_name\"}) by (deviceType, macAddress)\n* on (deviceType, macAddress) group_left(deviceName) \n  max(device_info{job=\"$job_name\"}) by (deviceType, macAddress, deviceName)",
     "legendFormat": "{{deviceName}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "device_info{job=\"$job_name\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpu_usage{job=\"$job_name\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_usage{job=\"$job_name\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "device_upgrade_needed{job=\"$job_name\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "device_last_seen{job=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}