{
 "title": "Switch",
 "tags": [ "Omada" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "increase_interval", "query": "${VAR_INCREASE_INTERVAL}" },
   { "name": "device_type", "query": "${VAR_DEVICE_TYPE}" },
   {
    "name": "port_ID",
    "query": {
     "query": "label_values(port_info{deviceType=\"$device_type\"},portID)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(port_tx_bytes_total{deviceType=\"$device_type\"}[$__range]) + \n    increase(port_rx_bytes_total{deviceType=\"$device_type\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(port_tx_bytes_total[$increase_interval]) + \n    rate(port_rx_bytes_total[$increase_interval])\n) / 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    count(port_speed{deviceType=\"$device_type\"} > 0) /\n    count(port_speed{deviceType=\"$device_type\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"$device_type\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage{deviceType=\"$device_type\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port $port_ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "port_ID",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_speed{deviceType=\"$device_type\", portID=\"$port_ID\"}\n  * on(macAddress, portID) group_left(portName, portMode)\nport_info{deviceType=\"$device_type\", portID=\"$port_ID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch port TX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n  (rate(port_tx_bytes_total{deviceType=\"$device_type\"}[$increase_interval]))\n  * on (macAddress, portID) group_left(portName, portMode)\n  max(port_info{deviceType=\"$device_type\"} == 1) by (macAddress, portID, portName, portMode)\n) / 8 ",
     "legendFormat": "{{portID}} - {{portName}}"
    }
   ]
  },
  {
   "title": "Switch port RX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n  (rate(port_rx_bytes_total{deviceType=\"$device_type\"}[$increase_interval]))\n  * on (macAddress, portID) group_left(portName, portMode)\n  max(port_info{deviceType=\"$device_type\"} == 1) by (macAddress, portID, portName, portMode)\n) / 8 ",
     "legendFormat": "{{portID}} - {{portName}}"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"$device_type\"}\n* on (macAddress) group_left(deviceName)\nmax(device_info{deviceType=\"$device_type\"} == 1) by (macAddress, deviceName)  ",
     "legendFormat": "{{deviceName}} (CPU)"
    },
    {
     "expr": "memory_usage{deviceType=\"$device_type\"}\n* on (macAddress) group_left(deviceName)\nmax(device_info{deviceType=\"$device_type\"} == 1) by (macAddress, deviceName)  ",
     "legendFormat": "{{deviceName}} (RAM)"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(port_tx_bytes_total[$increase_interval]) + \n    rate(port_rx_bytes_total[$increase_interval])\n) / 8",
     "legendFormat": "Switch Throughput"
    }
   ]
  }
 ]
}